package com.vmware.talentboost.springbootfinaltask.controller;

import com.vmware.talentboost.springbootfinaltask.data.Image;
import com.vmware.talentboost.springbootfinaltask.data.Tags;
import com.vmware.talentboost.springbootfinaltask.service.ImageService;
import com.vmware.talentboost.springbootfinaltask.service.TagService;
import org.springframework.web.bind.annotation.*;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.*;

@RestController // = @Controller + @ResponseBody
@RequestMapping("/images")
@CrossOrigin(origins = "http://localhost:4200")
public class ImageController {

    private final ImageService imageService;
    private final TagService tagService;

    public ImageController(final ImageService imageService, final TagService tagService){
        this.imageService = imageService;
        this.tagService = tagService;
    }

    /**
     * Creates an image.
     * <p>
     * Generated by Embold
     * 2022-05-21
     */
    @PostMapping
    public Image classify(@RequestBody final String request) throws URISyntaxException, IOException {
        Image image = imageService.classifyImage(request);
        return image;
    }
    @GetMapping("{id}")
    public Image get(@PathVariable final Integer id)  {
        try {
            return imageService.get(id);
        } catch (final NoSuchElementException e) {
            throw new IllegalArgumentException(
                    String.format("Project with ID %d not found.", id));
        }
    }
    @GetMapping
    public List<Image> get() {
        return imageService.getAll();
    }

    /*@GetMapping("tags")
    public List<Tags> getAllTags() {
        return tagService.getAll();
    }
    @GetMapping("{tag}")
    public Tags get(@PathVariable final String tag)  {
        try {
            return tagService.get(tag);
        } catch (final NoSuchElementException e) {
            throw new IllegalArgumentException(
                    String.format("Project with this tag: %s not found.", tag));
        }
    }*/
}
